//lalrpop이라는 라이브러리가 이해하는 스크립트임. 기본적으로 러스트 코드가 아니다.
//lalrpop라이브러리가 이 스크립트를 해석해서 이 문법을 파싱하는 러스트 코드를 만들어준다.
//코드를 짤 필요까지는 없지만 보고 읽을 수 있어야 한다.

//이 코드로 파싱을 해서 이런 Rust코드(즉, ExprParser 구조)가 자동으로 만들어 진다.

use std::str::FromStr;
use crate::ast::{Expr, Opcode};

grammar;

pub Expr: Box<Expr> = { //pub : 외부에서 사용될 수 있는 인터페이스라는 것. :전까지는 문법(grammar)의 세계(pub Expr). :이후부터는 Rust의 세계(Box<Expr> = )
    "(" <l:Expr> <op:ExprOp> <r:Expr> ")" => Box::new(Expr::Op(l, op, r)),  //=>전까지는 parser의 세계("(" <l:Expr> <op:ExprOp> <r:Expr> ")"),  =>이후부터는 Rust(Ast)의 세계(Box::new(Expr::Op(l, op, r)))
    <n:Num> => Box::new(Expr::Num(n)),
};

ExprOp: Opcode = { //:전까지는 문법(grammar)의 세계(ExprOp). :이후부터는 Rust의 세계(Opcode =)
    "+" => Opcode::Add,
    "-" => Opcode::Sub,
};

Num: i32 = {
    r"(-)?[0-9]+" => i32::from_str(<>).unwrap(), //r은 regex(Regular Expression)이라는 뜻 //매칭이 되면 string이 넘어감 <>는 r"(-)?[0-9]+" 여기서 매칭되어서 넘어오는 string을 의미, unwrap()은 예외처리
}

/*
//왼쪽(문법Grammar가 정의됨) 만약 왼쪽만 있다면 문법 검사만 해주는 parser가 생김

use std::str::FromStr;
use crate::ast::{Expr, Opcode};

grammar;

pub Expr:                                                           Box<Expr> = {
    "(" <l:Expr> <op:ExprOp> <r:Expr> ")"                           => Box::new(Expr::Op(l, op, r)), // Box::new 는 Box하나를 heap에다가 잡고 그걸 포인터에다가 넘겨주는 일종의 malloc 같은 역할을 하는 operation
    <n:Num>                                                         => Box::new(Expr::Num(n)),
};

ExprOp:                                                             Opcode = {
    "+"                                                             => Opcode::Add,
    "-"                                                             => Opcode::Sub,
};

Num:                                                                i32 = {
    r"(-)?[0-9]+"                                                   => i32::from_str(<>).unwrap(), 
}
*/